# This is a basic workflow to help you get started with Actions

name: LLMs-Prompt-Engineering

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Runs a single command using the runners shell
      - name: Checking
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:
          echo Add other actions to build,
          echo test, and deploy your project.
          #pip install -r requirements.txt
          #python app.py
          echo "## Model Metrics" > report.md
          #cat metrics.txt >> report.md
          
          echo "## Data viz" >>report.md
          #cml-publish feature_importance.png --md >> report.md
          #cml-publish residuals.png --md >> report.md
          
          cml-send-comment report.md
